### ISSUE TITLE
vector tiles aren't very fast.

### ISSUE THREAD

**Issue by dalekunce** [AmericanRedCross/GeoForce#244]
I expected the vector tiles to be super super fast and they aren't. Let's get ride of the on the fly merging and look at prebaking the tiles for the various themes.

**Comment by apollolm** [comment]
The bottleneck (I think) is in the merging of .json properties that get loaded when the page loads (or when the theme changes) and the array of vector tile features that have been fetched and are in memory.  The Vector Tiles themselves are already prebaked in Mapbox Studio (levels 0 thru 10 for level 0 and levels 0 - 14 for level 1).

You also can't necessarily bake the ECOS properties into the vector tiles, because your filters will change the counts and values.  If you baked the ecos properties into the vector tiles (or geojson) and then filter, we'd have to change filtering to be in the client rather than on the server (probably would be slow).

I'll try to improve performance by being better at the merge operation.  It's currently looping thru every Vector Tile feature and pulling properties from a dictionary using the ID as a key.  However, it's not necessary to loop thru every feature EVERY time.  A differential list should be kept of new incoming tile features that have yet to be symbolized, and ONLY those new ones are iterated over.  This should speed up the process.
