### ISSUE TITLE
Bubbles?

### ISSUE THREAD

**Issue by cwilkason** [AmericanRedCross/GeoForce#254]
Why are the bubbles over the disaster countries? Can we get rid of them?

**Comment by apollolm** [comment]
Bubbles indicate the number of disasters being responded to in a particular region.  We have since added a legend to explain the bubbles, as well as a new Disaster Type theme that shows not the count, but the type of disaster happening.  We've also tweaked the styling of the bubbles to hopefully make them less intrusive (they're smaller when zoomed out and get bigger when you zoom in).
