### ISSUE TITLE
Map upper right toolbar does not update accoringly each time

### ISSUE THREAD

**Issue by devinercolano** [AmericanRedCross/GeoForce#282]
When I use the MapUpperRighttoolbar and select certain countries under World/Region/Country option, the toolbar does not get updated with the country's name when they are selected.

'country' doesn’t update for the following places: 
Antarctica 
American Samoa 
Anguilla 
Antigua and Barbuda 
Bahamas 
Aruba, 
Benin,
Bonaire, Saint Eustatius, and Saba
British Indian Ocean Territory
British Virgin Island, Burundi
Canada, Cape Verde
Cayman Island
Chad
Chile
China
Cocos Island
Comoros
Cook Islands
Croatia
Curaçao
Ecuador
Equatorial Guinea
Faroe Islands
Fiji
French Polynesia
French Southern Territories
Gambia
Georgia
Gibraltar
Greece
Grenada (also no country name on map)
Guam
Guernsev
Haiti
Heard Island and McDonald Islands
Honduras
Indonesia
Israel
Italy
Japan
Kiribati
Laos
Liechtenstein
Malaysia
Maldives
Mali
Marshall Islands
Mauritius
Micronesia
New Caledonia
New Zealand
Norfolk Island
Northern Mariana
Norway
Palau
Peru
Pitcairn Islands
Puerto Rico
St Pierre and Miquelon
Saint Vincent and the Grenadines
Sao Tome and Principe
Seychelles
Slovenia
Soloman Islands
Somalia 
South Georgia and the South Sandwich Islands
Spain
Spratly Islands
Svalbard and Jan Mayen
Taiwan
Thailand
Togo
Tokelau
Tonga
Tunisia
Turks and Caicos Islands
Tuvalu
United Kingdom
UAE
US Minor Outlying Islands
Vanuatu
Vietnam
Virgin Islands
Wallis and Futuna
Zambia

**Comment by apollolm** [comment]
This is the expected behavior (albeit confusing).  The Label in the upper right changes to display whatever country is in the Center of the map view.  When you choose 'American Samoa', the map zooms to the islands of Samoa.  However, the center of the map happens to fall in the water, not Samoa, so the label doesn't change (since no new country is detected the map view).   This could be updated to use increasingly larger search areas - or if the center map query returns null, and we know that the user chose a country from the list, to just use that.

**Comment by dalekunce** [comment]
I'm happy with this as is.
