### ISSUE TITLE
suspect values in Custom filter in Projects theme

### ISSUE THREAD

**Issue by devinercolano** [AmericanRedCross/GeoForce#286]
The 'Filter Where Clause' option under the Custom tab in Project filters holds the default value of 'null' and takes on values that were used by the other tabs after they are manipulated.

**Comment by apollolm** [comment]
This is by design.  The Where clause is an optional filter that lets users enter SQL where clauses to filter the map.  By default it is empty (null).  Changing the other filters in other tabs creates SQL queries under the hood, so they're being shown in the 'where clause' panel so you can see what filters you have already chosen and add to it.  

I think this functionality is beyond most users of the system, and it might be less confusing if it were removed.

**Comment by dalekunce** [comment]
I actually like this feature and use it sometimes, but I'm not a normal user of the system
